apiVersion: apps/v1
kind: Deployment
metadata:
  name: dk-frontend
  labels:
    app: dk-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dk-frontend
  template:
    metadata:
      labels:
        app: dk-frontend
    spec:
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
      containers:
      - name: dk-frontend
        image: ghcr.io/bashfulrobot/runtime-vuln-workshop-assets-dk-frontend:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dk-frontend
  name: dk-frontend-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: dk-frontend
  type: NodePort
