apiVersion: apps/v1
kind: Deployment
metadata:
  name: dk-api
  labels:
    app: dk-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dk-api
  template:
    metadata:
      labels:
        app: dk-api
    spec:
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
      containers:
      - name: dk-api
        image: ghcr.io/bashfulrobot/runtime-vuln-workshop-assets-api:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dk-api-end
  name: dk-api-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: dk-api
  type: ClusterIP
